In [85]:
#Numpy basic
import numpy as np

# 1 d array 
arr = np.array([10, 20, 30, 40, 50])
# dimensionality, shape, number of elements
arr.ndim  # 1
arr.shape  # (5,)
len(arr)  # 5

5

In [86]:
# 2-dimensional array
arr_2dim = np.array([
    [10, 20, 30, 40, 50],
    [100, 200, 300, 400, 500]
])

# number of nested elements
arr_2dim.size  # 10

# type of object
type(arr_2dim)  

numpy.ndarray

In [87]:
# type of internal data
arr_2dim.dtype  

dtype('int32')

In [88]:
# element should be same type
# for nested arrays, inner arrays should have the same number 
np.array([1, 2, 3])  # good
np.array([1, 'bad', 'array', 2, 3])  # bad array

array(['1', 'bad', 'array', '2', '3'], dtype='<U11')

In [89]:
# good
np.array([
    [1, 2, 3, 4],
    [5, 6, 5, 7],
])  

array([[1, 2, 3, 4],
       [5, 6, 5, 7]])

In [90]:
# bad 
np.array([
    [1, 2, 3, 4],
    [5, 6]
])  #(1d array of 2 python lists, not  a 2d array)

array([list([1, 2, 3, 4]), list([5, 6])], dtype=object)

In [91]:
# nested lists
np.array([
    ['g', 'j'],
    ['c', 'd'],
    ['h', 'k']
])

array([['g', 'j'],
       ['c', 'd'],
       ['h', 'k']], dtype='<U1')

In [92]:
# 4x5 array of 0s 
np.zeros(shape = (4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [93]:
# initialize with any value
np.full(shape = (5, 5), fill_value = 'good')

array([['good', 'good', 'good', 'good', 'good'],
       ['good', 'good', 'good', 'good', 'good'],
       ['good', 'good', 'good', 'good', 'good'],
       ['good', 'good', 'good', 'good', 'good'],
       ['good', 'good', 'good', 'good', 'good']], dtype='<U4')

In [94]:
# sequence of integers from 1 to N
np.arange(start = 1, stop = 5, step = 1)  # start is inclusive,stop is exclusive

array([1, 2, 3, 4])

In [95]:
# random integers between 1 and 6
np.random.randint(low = 1, high = 7, size = (2, 3))

array([[4, 3, 2],
       [5, 1, 4]])

In [96]:
# array elements
newarr = np.array([10, 80, 30, 20, 100])
newarr[0]  

10

In [97]:
# modify  ith value
newarr[1] = -80  
newarr

array([ 10, -80,  30,  20, 100])

In [98]:
# access the last element in the array
newarr[4]  # 100

100

In [99]:
# access the last element in the array v2
newarr[len(newarr) - 1]  # 100

100

In [100]:
newarr[-1]  # last element 
newarr[-2]  # 2nd to last 

# out of bounds error
#newarr[999]  # error

20

In [101]:
# slicing
newarr[[0, 1, 4]]  
newarr[[0,1,0,1,0,1,0,1]]  
newarr[np.zeros(3, dtype = 'int64')] 

array([10, 10, 10])

In [102]:
# Slicing
newarr[:2]  
newarr[2:]  
newarr[::2] 

array([ 10,  30, 100])

In [103]:
# modify multiple elements
newarr[[0, 1, 4]] = [1000, 2005, 4500]  
newarr

array([1000, 2005,   30,   20, 4500])

In [104]:
# 3x4 array 
colrow = np.array([
    [15, 10, 15, 20],
    [25, 30, 100, 40],
    [45, 50, 55, 60]
])

# return the element at position (1,2)
colrow[1, 2]

# return row 1 as a 1d array
colrow[0]

# return row 1 as a 2d array
colrow[0, None]

# return the 2nd and 3rd columns in rows 2-3
colrow[1:3, [-2, -1]]

# replace element (0, 0) with -1
colrow[0, 0] = -1

# replace the 2nd row using the 3rd row
colrow[1] = colrow[2]

# insert 0s on diagonal
colrow[[0, 1, 2], [0, 1, 2]] = [0, 0, 0]
colrow

array([[ 0, 10, 15, 20],
       [45,  0, 55, 60],
       [45, 50,  0, 60]])

In [105]:
# make 2x2 arrays
narr = np.array([[2,1], [1,0]])
ncolrow = np.array([[6,2], [8,4]])

# addition
narr + ncolrow

# subtraction
narr - ncolrow

# multiplication
narr * ncolrow

# division
narr / ncolrow

# matrix multiplication, you can use the @ operator
narr @ ncolrow

array([[20,  8],
       [ 6,  2]])

In [106]:
#  4x3 array
bart = np.array([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3],
    [4, 4, 4]
])

lisa = np.array([
    [5, 3, 10],
    [5, 3, 10],
    [5, 3, 10],
    [5, 3, 10]
])
bart + lisa

array([[ 6,  4, 11],
       [ 7,  5, 12],
       [ 8,  6, 13],
       [ 9,  7, 14]])

In [107]:
# broadcasting
bart + np.array([[5, 3, 10]])

array([[ 6,  4, 11],
       [ 7,  5, 12],
       [ 8,  6, 13],
       [ 9,  7, 14]])

In [108]:
# shift,scale
np.array([1,2,3]) + 0.5  # [1.5, 2.5, 3.5]
np.array([1,2,3]) * -1   # [-1, -2, -3]

# add bart to a 4 element vector, error
#bart + np.array([1, 2, 3, 4])  

array([-1, -2, -3])

In [109]:
# martrix work
#v1
np.random.seed(123)
A = np.random.randint(low = 1, high = 10, size = (3, 4))
B = np.random.randint(low = 1, high = 10, size = (3, 1))

A.shape  # (3, 4)
B.shape  # (3, 1)
#           ^  ^
#         compatible

(3, 1)

In [110]:
#v2
np.random.seed(321)
A = np.random.randint(low = 1, high = 10, size = (4, 4))
B = np.random.randint(low = 1, high = 10, size = (2, 1))

A.shape  # (4, 4)
B.shape  # (2, 1)
#           ^  ^
#         not compatible
#A*B #error

(2, 1)

In [111]:
# v3
np.random.seed(1111)
A = np.random.randint(low = 1, high = 10, size = (3, 1, 4))
B = np.random.randint(low = 1, high = 10, size = (2, 1))

A.shape  # (3, 1, 4)
B.shape  # (   2, 1)
#           ^  ^  ^
#         compatible
A*B

array([[[72, 54, 18, 27],
        [32, 24,  8, 12]],

       [[45, 81, 63, 45],
        [20, 36, 28, 20]],

       [[81, 63, 27, 63],
        [36, 28, 12, 28]]])

In [112]:
# Deduct
A = np.array([3, 11, 4, 5])
B = np.array([5, 0, 3])
 
A[np.newaxis, :] - B[:, np.newaxis]

array([[-2,  6, -1,  0],
       [ 3, 11,  4,  5],
       [ 0,  8,  1,  2]])

In [113]:
# using None
A[None, :] - B[:, None]

array([[-2,  6, -1,  0],
       [ 3, 11,  4,  5],
       [ 0,  8,  1,  2]])

In [114]:
# make 2x2 arrays
newarr = np.array([[2,3], [1,2]])
colrow = np.array([[3,2], [1,4]])

# addition
newarr + colrow

# subtraction
newarr - colrow

array([[-1,  1],
       [ 0, -2]])

In [115]:
# reshape
nnarr = np.arange(start = 2, stop = 10)  
nnarr 

array([2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
nncolrow = nnarr.reshape((2,4))
nncolrow = np.reshape(a = nnarr, newshape = (2,4))

In [117]:
# slightly different interfaces
nnarr.reshape(2,4)  # allowed
#nnarr.reshape(newshape = (2,4))  # error


# C-style order reorders the last axis first
nncolrow.reshape((4,2), order = 'C')

# Fortran-style order reorders the first axis first
nncolrow.reshape((4,2), order = 'F')

# transpose 
nncolrow.T

array([[2, 6],
       [3, 7],
       [4, 8],
       [5, 9]])

In [118]:
# reshape into higher dimensions
nncolrow.reshape((2,2,2))

#nncolrow.reshape((2,2,3)) # error

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

In [119]:
# use -1 for  newshape dimensions 
nncolrow.reshape((-1, 2))

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [120]:
# 3x3 array of positive integers. we want tocreplace every 3 with 0
nnnarr = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])

# Checking nnnarr == 3, numpy gives us a 3x3 array of boolean values
check = nnnarr == 3

# Now we can use this array of boolean values to index our original array, identify which elements are 3
nnnarr[check]
nnnarr[check] = 0
nnnarr

# pick out specific rows or columns
rows_1_and_3 = np.array([True, False, True])
cols_2_and_3 = np.array([False, True, True])
nnnarr[rows_1_and_3]  # returns rows 1 and 3
nnnarr[:, cols_2_and_3]  # returns cols 2 and 3

array([[9, 7],
       [0, 0],
       [0, 1]])

In [121]:
#multiple boolean indexes 
nnnarr[rows_1_and_3, cols_2_and_3] # equivalent to nnnarr[[0,2], [1,2]]

array([9, 1])

In [122]:
# combine boolean arrays using bitwise operators
b1 = np.array([False, False, True, True])
b2 = np.array([False, True, False, True])
b1 & b2  # [False, False, False,  True]  # and
b1 | b2  # [False,  True,  True,  True]  # or
b1 ^ b2  # [False,  True,  True, False]  # xor

# negation
~np.array([False, True])

# Examples
name = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
age = np.array([43, 84, 43, 52, 74])
sex = np.array(['male', 'female', 'male', 'male', 'male'])

#inquiry
name[age >= 43]
name[(sex == "male") & (age > 43)]
name[~(sex == "male") | (age < 52)]

array(['Dennis', 'Dee', 'Charlie'], dtype='<U7')

In [123]:
# np.nan 
arr = np.ones(shape = (3, 4))
arr[[0, 2], [1, 2]] = np.nan
arr

# check arr == np.nan
arr == np.nan
np.nan == np.nan  # False
np.nan != np.nan  # True

# check nan elements
np.isnan(arr)

# only works for for arrays of floats
narr = np.array([1, 2, 3], dtype = 'int64')
#narr[1] = np.nan  # error
narr

array([1, 2, 3], dtype=int64)

In [124]:
# np.inf and np.NINF
np.array([np.inf, np.NINF])  # [ inf, -inf]
# occur when divide by 0
np.array([-1, 1])/0  # [-inf,  inf]

D:\Program\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


array([-inf,  inf])

In [125]:
# 
np.inf * 100  # inf
np.inf + np.inf # inf
np.inf - np.inf  # nan
np.inf / np.inf    # nan

# 
np.inf == np.inf   # True
np.NINF == np.NINF # True

# isolate infinite values 
arr = np.array([4.4, np.inf, 1.0, np.NINF, 3.1, np.inf])
arr == np.inf  # [False,  True, False, False, False,  True]
arr == np.NINF # [False, False, False,  True, False, False]

# Alternatively,
np.isposinf(arr)  # [False,  True, False, False, False,  True]
np.isneginf(arr)  # [False, False, False,  True, False, False]
np.isinf(arr)     # [False,  True, False,  True, False,  True]

array([False,  True, False,  True, False,  True])

In [140]:
#simulate
np.random.randint(low=1, high=7, size=3)  

np.random.seed(123)
np.random.randint(low=1, high=7, size=3)  
np.random.randint(low=1, high=7, size=3)  
np.random.seed(2357)
np.random.randint(low=1, high=7, size=3) 
np.random.randint(low=1, high=7, size=3)  

# draw values without relpacement
np.random.seed(123)
np.random.choice(
    a = np.arange(1, 7),
    size = 3,
    replace = False,
    p = None
)  # [6, 5, 1]

# draw values with probabilities
np.random.choice(
    a = np.arange(1, 7),
    size = 3,
    replace = False,
    p = np.array([0.1, 0.1, 0.1, 0.1, 0.3, 0.3])
)  # [5, 2, 6]

# draw values from strings
np.random.choice(
    a = np.array(['you', 'can', 'use', 'strings', 'too']),
    size = 3,
    replace = False,
    p = None
)  

array(['strings', 'you', 'too'], dtype='<U7')

In [127]:
# random
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]
])

# with replacement
np.random.seed(123)
rand_rows = np.random.randint(
    low=0,
    high=arr.shape[0],
    size=3
)  
arr[rand_rows]

# without replacement
rand_rows = np.random.choice(
    a=np.arange(start=0, stop=arr.shape[0]),
    replace=False,
    size=3
) 
arr[rand_rows]

# row-wise shuffle
np.random.permutation(arr)

#uniform()
np.random.uniform(low = 1.0, high = 2.0, size = (2, 2))

#normal distribution
np.random.normal(loc = 0.0, scale = 1.0, size = 2)

## binomial() 
np.random.binomial(n = 10, p = 0.25, size = (3, 2))

#https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html

array([[3, 3],
       [3, 2],
       [1, 3]])

In [128]:
# 3rd array, loop
arr = np.array([1, 2, 3, 4, 5])
narr = np.array([0, 1, 0, 0, 1])

a3 = np.zeros(arr.shape[0])
for i in range(arr.shape[0]):
    if narr[i] == 0:
        a3[i] = 2 * arr[i]
    else:
        a3[i] = arr[i] / 2

# where() 
a3 = np.where((narr == 0), arr * 2.0, arr / 2.0)
a3

array([2. , 1. , 6. , 8. , 2.5])

In [141]:
arra = np.array(
    [[23.0, 2.0, 20.0],
     [1.0, 9.0, 2.0],
     [1.0, 7.0, 52.0]]
)
# sum
np.sum(arra)  
# sum by  rows, columns
np.sum(arra, axis = 0)  # sum across axis 0 (column sums)
np.sum(arra, axis = 1)  # sum across axis 1 (row sums)
# keepdims
np.sum(arra, axis = 0, keepdims=True)  
# sum with nans
arra[0, 0] = np.nan
np.sum(arra)  # sum across axis 1 (row sums) nan
# sum excluding nans
np.sum(arra, where = ~np.isnan(arra))  
# alternative
np.nansum(arra) 

94.0

In [130]:
#nan
arr = np.array([
    [np.nan, 1.5],
    [2.0, 1.3],
    [np.nan, np.nan],
    [8.1, np.nan]
])
#at least one nan value
narr = np.any(np.isnan(arr), axis = 1)
arr[narr]

# all nan values
narr = np.all(np.isnan(arr), axis = 1)
arr[narr]

array([[nan, nan]])

In [131]:
#concatenate
arr = np.zeros(shape = (3, 2))
narr = np.ones(shape = (2,2))
np.concatenate((arr, arr, arr), axis = 0)

np.concatenate((arr, arr, arr), axis = 1)
np.concatenate((arr, narr), axis = 0)
# error
#np.concatenate((arr, narr), axis = 1)  

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [132]:
#stack
arr = np.array(['a', 'b'])
narr = np.array(['c', 'd'])
nnarr = np.array([['e', 'f']])
arr0 = np.array([['g', 'h', 'i']])
arr1 = np.array(
    [['j', 'k'],
     ['l', 'm']]
)

# vstack 
np.vstack((arr, narr))
np.vstack((arr, narr, nnarr))
 # error
#np.vstack((nnarr, arr0)) 

# hstack
np.hstack((arr, narr))
np.hstack((nnarr, arr0))
# error
#np.hstack((arr, arr0))  
# error
#np.hstack((arr0, arr1))  

# stack along axis 0
np.stack((arr, narr), axis = 0)

# stack along axis 1
np.stack((arr, narr), axis = 1)

# stack arr along axis 2 #error
#np.stack((arr, narr), axis = 2)
# Use axis = -1 to insert the new axis to end 
np.stack((arr, narr), axis = -1)

array([['a', 'c'],
       ['b', 'd']], dtype='<U1')

In [133]:
# sort 
arr = np.array([1, 17, 2, 660, 0, 99, 66])
np.sort(arr)

narr = np.array([20, np.nan, 3, 11])
np.sort(narr) 

np.sort(narr)[::-1]  # reverse the sorted array
-np.sort(-narr)      # negate the sorted values of the negated array

# kind = 'stable'
np.sort(np.array([2, 1, 3, 2]), kind='stable')

# 2d array
alpha = np.array([
    [66, 20, 12],
    [0, 81, 33],
    [92, 11, 3]
])
np.sort(a = alpha, axis = 0)   # sorts by row axis
np.sort(a = alpha, axis = 1)   # sorts by column axis
np.sort(a = alpha, axis = -1)  # (default) sorts by last axis (in this case, the column axis)

# sort the rows of arr based on the values in the 1st column
alpha[np.array([1, 0, 2])]

# argsort()
beta = np.array([3, 0, 66, 20])  
np.argsort(beta)                
np.sort(beta)                  

# sort a 2d array's rows based on a certain column
alpha[np.argsort(alpha[:, 1])]   # sort by column 1 ascending
alpha[np.argsort(-alpha[:, -1])]  # sort by last column, descending

array([[ 0, 81, 33],
       [66, 20, 12],
       [92, 11,  3]])

In [134]:
# unique value
arr = np.array(['b', 'b', 'a', 'a', 'c', 'c'])

np.unique(arr)   # ['a', 'b', 'c', 'nan']

# sort 
uniques, first_positions = np.unique(arr, return_index = True)
uniques[np.argsort(first_positions)]  # ['b', 'a', 'c']

# counts
np.unique(arr, return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 2], dtype=int64))

In [135]:
#create a column based on existing
import numpy as np
np.random.seed(123)
arr = np.random.uniform(low = 0.0, high = 1.0, size = (10, 2))
arr[np.random.randint(low = 0, high = 10, size = 5), np.repeat(0, 5)] = np.nan
arr = np.round(arr, 2)
narr = np.where(np.isnan(arr[:, 0]), arr[:, 1], arr[:, 0])
out = np.insert(arr = arr, obj = 2, values = narr, axis = 1)
# alternative
out = np.hstack((arr, narr[:, None]))
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [136]:
# identify indicated value
alpha = np.array([0, 15, 32, 11, 5, 5, 24, 99, 81, 3, 45, 9, 41])
alpha[(alpha < 10).nonzero()[0][:3]] = 0
alpha

array([ 0, 15, 32, 11,  0,  0, 24, 99, 81,  3, 45,  9, 41])

In [137]:
# Insert random
sol = np.zeros(shape = (5, 5))
np.random.seed(123)
val = np.random.normal(size = 10)
location = np.random.choice(sol.size, len(val), replace = False)
sol.ravel()[location] = val
np.round(sol, 2)

array([[ 0.  , -0.58,  0.  ,  0.  ,  0.  ],
       [-1.51,  1.65,  0.  ,  0.  , -2.43],
       [ 1.  , -1.09, -0.43,  0.28,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.27,  0.  ],
       [ 0.  ,  0.  ,  0.  , -0.87,  0.  ]])

In [138]:
#fill the rows of array based on another.
alpha = np.zeros(shape = (4, 5))
beta = np.array([3, 0, 4, 1])
(beta[:, None] <= np.arange(alpha.shape[1])).astype('int')

array([[0, 0, 0, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 1, 1, 1]])

In [139]:
#convert 1d to 2d
alpha = np.array([3, 1, 0, 1])
# v1
groups = np.max(alpha) + 1
out = np.eye(groups)[alpha]
# v2
out = np.zeros(shape = (len(alpha), groups))
out[np.arange(out.shape[0]), alpha] = 1
out


array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])